/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prolab3;

/**
 *
 * @author ahmet
 */
public class MudurFrame extends javax.swing.JFrame {

    Mudur mudurislemi= new Mudur();
    
    
    
    public MudurFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        eklenecekparabirimialani = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kurfiyatıalani = new javax.swing.JTextField();
        parabirimieklebuton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        guncellenecekkuralani = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        guncelkurfiyatialani = new javax.swing.JTextField();
        kurguncellebuton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        guncellenecekcalisanmaasalani = new javax.swing.JTextField();
        maasguncellebuton = new javax.swing.JButton();
        müşterieklebuton = new javax.swing.JButton();
        musterigoruntulebuton = new javax.swing.JButton();
        hesapgoruntulebuton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Eklenecek Para Birimi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Kur Fiyatı");

        parabirimieklebuton.setBackground(new java.awt.Color(255, 102, 102));
        parabirimieklebuton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        parabirimieklebuton.setText("Ekle");
        parabirimieklebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parabirimieklebutonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Güncellenecek Kur");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Güncel Kur");

        kurguncellebuton.setBackground(new java.awt.Color(255, 102, 102));
        kurguncellebuton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kurguncellebuton.setText("Güncelle");
        kurguncellebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurguncellebutonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Çalışan Maaşı Güncelle");

        maasguncellebuton.setBackground(new java.awt.Color(255, 51, 51));
        maasguncellebuton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maasguncellebuton.setText("Güncelle");
        maasguncellebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maasguncellebutonActionPerformed(evt);
            }
        });

        müşterieklebuton.setBackground(new java.awt.Color(255, 51, 51));
        müşterieklebuton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        müşterieklebuton.setText("Müşteri Ekle");
        müşterieklebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                müşterieklebutonActionPerformed(evt);
            }
        });

        musterigoruntulebuton.setBackground(new java.awt.Color(255, 102, 102));
        musterigoruntulebuton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        musterigoruntulebuton.setText("Müşterileri Görüntüle");
        musterigoruntulebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musterigoruntulebutonActionPerformed(evt);
            }
        });

        hesapgoruntulebuton.setBackground(new java.awt.Color(255, 51, 51));
        hesapgoruntulebuton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hesapgoruntulebuton.setText("Müşteri Hesaplarını Görüntüle");
        hesapgoruntulebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesapgoruntulebutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eklenecekparabirimialani)
                    .addComponent(guncellenecekkuralani)
                    .addComponent(guncellenecekcalisanmaasalani))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(maasguncellebuton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kurfiyatıalani)
                    .addComponent(guncelkurfiyatialani, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parabirimieklebuton)
                    .addComponent(kurguncellebuton))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(müşterieklebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(musterigoruntulebuton)
                .addGap(18, 18, 18)
                .addComponent(hesapgoruntulebuton)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eklenecekparabirimialani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(kurfiyatıalani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parabirimieklebuton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(guncellenecekkuralani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(guncelkurfiyatialani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kurguncellebuton))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(guncellenecekcalisanmaasalani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maasguncellebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(müşterieklebuton)
                    .addComponent(musterigoruntulebuton)
                    .addComponent(hesapgoruntulebuton))
                .addContainerGap(259, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parabirimieklebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parabirimieklebutonActionPerformed
        
      String  parabirimiad= eklenecekparabirimialani.getText();
      
      String parabirimifiyatt= kurfiyatıalani.getText();
      
      int parabirimifiyat= Integer.parseInt(parabirimifiyatt);
        
      mudurislemi.parabirimiekle(parabirimiad, parabirimifiyat);
      
              
    }//GEN-LAST:event_parabirimieklebutonActionPerformed

    private void kurguncellebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurguncellebutonActionPerformed
        
        String parabirimiad= guncellenecekkuralani.getText();
        
        String yenikurfiyatt = guncelkurfiyatialani.getText();
        
        int parabirimifiyat= Integer.parseInt(yenikurfiyatt);
        
        mudurislemi.parabirimiguncelle(parabirimiad, parabirimifiyat);
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_kurguncellebutonActionPerformed

    private void maasguncellebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maasguncellebutonActionPerformed
       
       String guncellenecekmaass = guncellenecekcalisanmaasalani.getText();
       
       
       int guncellenecekmaas= Integer.parseInt(guncellenecekmaass);
       
       mudurislemi.maasguncelle(guncellenecekmaas);
    
        
        
    }//GEN-LAST:event_maasguncellebutonActionPerformed

    private void müşterieklebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_müşterieklebutonActionPerformed
        
        MusteriEkleFrame frame = new MusteriEkleFrame();
        
        frame.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_müşterieklebutonActionPerformed

    private void musterigoruntulebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musterigoruntulebutonActionPerformed
          
        MusteriGoruntule musterigoruntule=new MusteriGoruntule();

        musterigoruntule.setVisible(true);
      
        
        
    }//GEN-LAST:event_musterigoruntulebutonActionPerformed

    private void hesapgoruntulebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesapgoruntulebutonActionPerformed
        HesapGoruntule hesaplar = new HesapGoruntule();
        hesaplar.setVisible(true);
        
    }//GEN-LAST:event_hesapgoruntulebutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MudurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MudurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MudurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MudurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MudurFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eklenecekparabirimialani;
    private javax.swing.JTextField guncelkurfiyatialani;
    private javax.swing.JTextField guncellenecekcalisanmaasalani;
    private javax.swing.JTextField guncellenecekkuralani;
    private javax.swing.JButton hesapgoruntulebuton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField kurfiyatıalani;
    private javax.swing.JButton kurguncellebuton;
    private javax.swing.JButton maasguncellebuton;
    private javax.swing.JButton musterigoruntulebuton;
    private javax.swing.JButton müşterieklebuton;
    private javax.swing.JButton parabirimieklebuton;
    // End of variables declaration//GEN-END:variables
}
