/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prolab3;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmet
 */






public class MusteriFrame extends javax.swing.JFrame {

    
      
      Musteri musteriislemi= new Musteri();
   
    
   
    
    
    public MusteriFrame() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        paracekmealani = new javax.swing.JTextField();
        paracekbuton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        yatiralacakparaalani = new javax.swing.JTextField();
        parayatirbuton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        aktarilacakparamiktarialani = new javax.swing.JTextField();
        paraaktarbuton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        aktarilacakhesapalani = new javax.swing.JTextField();
        hesapsilbuton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        islemyapilacakhesapalani = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        musteritcnoalani = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        adresguncellemealani = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        telefonguncellemealani = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        epostaguncellemealani = new javax.swing.JTextField();
        adresguncellemebutonu = new javax.swing.JButton();
        telefonguncellemebutonu = new javax.swing.JButton();
        epostaguncellemebutonu = new javax.swing.JButton();
        krediborcuodebuton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        odenecekkredimiktarıalani = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Çekilecek Para Miktarı");

        paracekbuton.setBackground(new java.awt.Color(255, 51, 51));
        paracekbuton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paracekbuton.setText("Para Çek");
        paracekbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paracekbutonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Yatıralacak Para Miktarı");

        yatiralacakparaalani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yatiralacakparaalaniActionPerformed(evt);
            }
        });

        parayatirbuton.setBackground(new java.awt.Color(255, 51, 51));
        parayatirbuton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        parayatirbuton.setText("Para Yatır");
        parayatirbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parayatirbutonActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 51, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Aktarılacak Para Miktarı");

        paraaktarbuton.setBackground(new java.awt.Color(255, 51, 51));
        paraaktarbuton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paraaktarbuton.setText("Para Aktar");
        paraaktarbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraaktarbutonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Hedef Hesap");

        hesapsilbuton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hesapsilbuton.setText("Hesap Sil");
        hesapsilbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesapsilbutonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("İşlem Yapılacak Hesap Numaranız");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Güncelleme İşlemi İçin Tc No Girin");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Adres");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Telefon");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("E Posta");

        adresguncellemebutonu.setBackground(new java.awt.Color(255, 0, 51));
        adresguncellemebutonu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adresguncellemebutonu.setText("Güncelle");
        adresguncellemebutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresguncellemebutonuActionPerformed(evt);
            }
        });

        telefonguncellemebutonu.setBackground(new java.awt.Color(255, 0, 0));
        telefonguncellemebutonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telefonguncellemebutonu.setText("Güncelle");
        telefonguncellemebutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonguncellemebutonuActionPerformed(evt);
            }
        });

        epostaguncellemebutonu.setBackground(new java.awt.Color(255, 51, 51));
        epostaguncellemebutonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        epostaguncellemebutonu.setText("Güncelle");
        epostaguncellemebutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epostaguncellemebutonuActionPerformed(evt);
            }
        });

        krediborcuodebuton.setBackground(new java.awt.Color(255, 51, 51));
        krediborcuodebuton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        krediborcuodebuton.setText("Kredi Borcu Öde");
        krediborcuodebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krediborcuodebutonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Ödemek İstediğiniz Kredi Borcu Miktarı");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(islemyapilacakhesapalani, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(musteritcnoalani)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(paracekmealani, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(yatiralacakparaalani, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paracekbuton)
                                    .addComponent(parayatirbuton)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adresguncellemealani)
                                    .addComponent(telefonguncellemealani)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(epostaguncellemealani)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aktarilacakparamiktarialani, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aktarilacakhesapalani, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paraaktarbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(telefonguncellemebutonu)
                                            .addComponent(adresguncellemebutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(epostaguncellemebutonu))
                                        .addGap(114, 114, 114))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(odenecekkredimiktarıalani, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hesapsilbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(krediborcuodebuton, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(362, 362, 362))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(musteritcnoalani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(islemyapilacakhesapalani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paracekmealani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(paracekbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yatiralacakparaalani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parayatirbuton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(aktarilacakparamiktarialani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(aktarilacakhesapalani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paraaktarbuton))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(adresguncellemealani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adresguncellemebutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hesapsilbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(telefonguncellemealani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonguncellemebutonu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(epostaguncellemealani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(epostaguncellemebutonu))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(krediborcuodebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(odenecekkredimiktarıalani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(585, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yatiralacakparaalaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yatiralacakparaalaniActionPerformed
     
   
        
    }//GEN-LAST:event_yatiralacakparaalaniActionPerformed

    private void paracekbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paracekbutonActionPerformed
        
        
        String islemyapilacakhesap = islemyapilacakhesapalani.getText();
        String cekilecekparaa = paracekmealani.getText();
        
        int cekilecekpara= Integer.parseInt(cekilecekparaa);
        
      
        
        
       
        
        musteriislemi.paracekme(islemyapilacakhesap,cekilecekpara);
        
       
        
    }//GEN-LAST:event_paracekbutonActionPerformed

    private void parayatirbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parayatirbutonActionPerformed
      
        String islemyapilacakhesap= islemyapilacakhesapalani.getText();
        String yatirilacakparaa= yatiralacakparaalani.getText();
        
        int yatirilacakpara=Integer.parseInt(yatirilacakparaa);
        
        musteriislemi.parayatirma(islemyapilacakhesap,yatirilacakpara);
    }//GEN-LAST:event_parayatirbutonActionPerformed

    private void paraaktarbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraaktarbutonActionPerformed
        
        String islemyapilacakhesap= islemyapilacakhesapalani.getText();
        
        String aktarilacakhesap=aktarilacakhesapalani.getText();
        
        String aktarilacakparaa=aktarilacakparamiktarialani.getText();
        
        
        int aktarilacakpara=Integer.parseInt(aktarilacakparaa);
        
        
        musteriislemi.paracekme(islemyapilacakhesap, aktarilacakpara);
        
        musteriislemi.parayatirma(aktarilacakhesap, aktarilacakpara);
        
        
    }//GEN-LAST:event_paraaktarbutonActionPerformed

    private void hesapsilbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesapsilbutonActionPerformed
       
        String islemyapilacakhesap=islemyapilacakhesapalani.getText();
        
        
        
        musteriislemi.hesapsil(islemyapilacakhesap);
        
        
      
        
    }//GEN-LAST:event_hesapsilbutonActionPerformed

    private void adresguncellemebutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresguncellemebutonuActionPerformed
        
        String guncellenecekadres= adresguncellemealani.getText();
        String musteritcno= musteritcnoalani.getText();
        
        musteriislemi.adresguncelle(musteritcno,guncellenecekadres);
        
        
        
        
        
    }//GEN-LAST:event_adresguncellemebutonuActionPerformed

    private void telefonguncellemebutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonguncellemebutonuActionPerformed
       
        String guncellenecektelefon=telefonguncellemealani.getText();
        String musteritcno= musteritcnoalani.getText();
        
        musteriislemi.telefonguncelle(musteritcno,guncellenecektelefon);
        
        
        
        
        
    }//GEN-LAST:event_telefonguncellemebutonuActionPerformed

    private void epostaguncellemebutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epostaguncellemebutonuActionPerformed
         
        String musteritcno= musteritcnoalani.getText();
        String guncellenecekeposta= epostaguncellemealani.getText();
        musteriislemi.epostaguncelle(musteritcno,guncellenecekeposta);
        
        
        
    }//GEN-LAST:event_epostaguncellemebutonuActionPerformed

    private void krediborcuodebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krediborcuodebutonActionPerformed
        
        String musterihesapno= islemyapilacakhesapalani.getText();
        String odenecekkredimiktarii=odenecekkredimiktarıalani.getText();
        int odenecekkredimiktari=Integer.parseInt(odenecekkredimiktarii);
        
        musteriislemi.krediborcuode(musterihesapno,odenecekkredimiktari);
        
        
        
        
        
        
        
    }//GEN-LAST:event_krediborcuodebutonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresguncellemealani;
    private javax.swing.JButton adresguncellemebutonu;
    private javax.swing.JTextField aktarilacakhesapalani;
    private javax.swing.JTextField aktarilacakparamiktarialani;
    private javax.swing.JTextField epostaguncellemealani;
    private javax.swing.JButton epostaguncellemebutonu;
    private javax.swing.JButton hesapsilbuton;
    private javax.swing.JTextField islemyapilacakhesapalani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton krediborcuodebuton;
    private javax.swing.JTextField musteritcnoalani;
    private javax.swing.JTextField odenecekkredimiktarıalani;
    private javax.swing.JButton paraaktarbuton;
    private javax.swing.JButton paracekbuton;
    private javax.swing.JTextField paracekmealani;
    private javax.swing.JButton parayatirbuton;
    private javax.swing.JTextField telefonguncellemealani;
    private javax.swing.JButton telefonguncellemebutonu;
    private javax.swing.JTextField yatiralacakparaalani;
    // End of variables declaration//GEN-END:variables
}
